security:
  encoders:
    App\Entity\User:
      algorithm: auto

  providers:
    # used to reload user from session & other features (e.g. switch_user)
    auth_provider:
      chain:
        providers: [ldap_user_provider, database_user_provider]
    database_user_provider:
      entity:
        class: App\Entity\User
        property: username
    ldap_user_provider:
      id: App\Security\LdapProvider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      provider: auth_provider
      guard:
        authenticators:
          - App\Security\UserAuthenticator

      logout:
        path: user_logout
  access_control:
    - { path: ^/_/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/_/user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/_/public, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/_install, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: ROLE_USER, allow_if: "isSecurityDisabled()"}
